language: c++
compiler:
  - clang
  - gcc

script:
  - cd test && wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp && cd ..
  - mkdir build && cd $_
  - cmake ..
  - cmake --build .
  - ./string_literal_test
